// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVCCodeFirst.Models;

#nullable disable

namespace WebMVCCodeFirst.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20230421131158_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMVCCodeFirst.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("WebMVCCodeFirst.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("money");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("WebMVCCodeFirst.Models.Responsible", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Responsibles", (string)null);
                });

            modelBuilder.Entity("WebMVCCodeFirst.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("WebMVCCodeFirst.Models.Product", b =>
                {
                    b.HasOne("WebMVCCodeFirst.Models.Model", "Model")
                        .WithMany("Products")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Product_Model");

                    b.HasOne("WebMVCCodeFirst.Models.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Product_Store");

                    b.Navigation("Model");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("WebMVCCodeFirst.Models.Store", b =>
                {
                    b.HasOne("WebMVCCodeFirst.Models.Responsible", "Responsible")
                        .WithMany("Stores")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Store_Responsible");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("WebMVCCodeFirst.Models.Model", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebMVCCodeFirst.Models.Responsible", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("WebMVCCodeFirst.Models.Store", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
