//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public string Categorie { get; set; }
        public Nullable<decimal> Prix { get; set; }
    }
}
